### ISSUE TITLE
Chaining of Monitors to use Detector Triggers in Bucket Level Monitors

### ISSUE THREAD

**Issue by sbcd90** [opensearch-project/security-analytics#192]
@eirsep

**Comment by eirsep** [comment]
Being tracked in #219

**Comment by eirsep** [comment]
```
{
  "type": "detector",
  "detector_type": "s3",
  "name": "s3access_detector",
  "enabled": true,
  "createdBy": "chip",
  "schedule": {
    "period": {
      "interval": 1,
      "unit": "MINUTES"
    }
  },
  "inputs": [    {
      "input": {
        "description": "s3access detector for security analytics",
        "indices": [
          "s3"
        ],
        "custom_rules": [
        ],
        "pre_packaged_rules": [
          {
            "id": "0f6c1bf5-70a5-4963-aef9-aab1eefb50bd"
          }
        ]
      }
    }

  ],
  "triggers": [
    {
      "ids": [
        "0f6c1bf5-70a5-4963-aef9-aab1eefb50bd"
      ],
      "types": [],
      "tags": [
        "attack.exfiltration"
      ],
      "severity": "1",
      "actions": [{
          "id": "hVTLkZYzlA",
          "destination_id": "6r8ZBoQBKW_6dKriacQb",
          "subject_template": {
            "source": "Detector {{ctx.detector.name}} just entered alert status",
            "lang": "mustache"
          },
          "name": "hello_world",
          "throttle_enabled": false,
          "message_template": {
            "source": "Detector {{ctx.detector.name}} just entered alert status. Please investigate the issue.\n - Trigger: {{ctx.trigger.name}}\n - Severity: {{ctx.trigger.severity}}",
            "lang": "mustache"
          },
          "throttle": {
            "unit": "MINUTES",
            "value": 108
          }
        }
      ],
      "id": "8qhrBoQBYK1JzUUDzH-N",
      "sev_levels": [],
      "name": "test-trigger"
    }
  ]
}
```
```
title: High DNS Bytes Out
id: 0f6c1bf5-70a5-4963-aef9-aab1eefb50bd
status: test
description: High DNS queries bytes amount from host per short period of time
author: Daniil Yugoslavskiy, oscd.community
date: 2019/10/24
modified: 2022/10/09
tags:
    - attack.exfiltration
    - attack.t1048.003
logsource:
    category: dns
detection:
    selection:
        query: '*'
    timeframe: 1m
    condition: selection | sum(question_length) by src_ip > 300000
falsepositives:
    - Legitimate high DNS bytes out rate to domain name which should be added to whitelist
level: medium
```
```
{
  "type": "monitor",
  "name": "alert-demo-6",
  "monitor_type": "bucket_level_monitor",
  "enabled": true,
  "schedule": {
    "period": {
      "interval": 1,
      "unit": "MINUTES"
    }
  },
  "inputs": [
    {
      "search": {
        "indices": [
          "sample-http-responses"
        ],
        "query": {
          "size": 1,
          "query": {
            "match_all": {}
          },
          "aggs": {
            "question_length_sum": {
              "terms": {
                "field": "src_ip"
              },
              "aggs": {
                "question_length": {
                  "sum": {
                    "field": "question_length"
                  }
                }
              }
            }
          }
        }
      }
    }
  ],
  "triggers": [
    {
      "bucket_level_trigger": {
        "name": "trigger-demo-6",
        "severity": "1",
        "condition": {
          "buckets_path": {
            "question_length": "question_length"
          },
          "parent_bucket_path": "question_length_sum",
          "script": {
            "source": "params.question_length > 300000",
            "lang": "painless"
          }
        },
        "actions": []
      }
    }
  ]
}
```
