### ISSUE TITLE
[BUG] Invalid condition for 1 of pattern, all of pattern condition

### ISSUE THREAD

**Issue by yblee85** [opensearch-project/security-analytics#987]
## Not sure if this is a bug or feature request.

**What is the bug?**
[Sigma documentation ( Advanced Conditions )](https://sigmahq.io/docs/basics/conditions.html#_1-of-search-pattern)
`condition: 1 of selection*` 

**How can one reproduce the bug?**
1. Go to /app/opensearch_security_analytics_dashboards#/import-rule
2. Import Rule
3. Import following rule
```
title: DEWMODE Webshell Access
description: Detects access to DEWMODE webshell as described in FIREEYE report
logsource:
    category: webserver
detection:
    selection1:
        c-uri|contains|all:
            - '?dwn='
            - '&fn='
            - '.html?'
    selection2:
        c-uri|contains|all:
            - '&dwn='
            - '?fn='
            - '.html?'
    condition: 1 of selection*
```

**What is the expected behavior?**
It should allow

**What is your host/environment?**
 - OS: ubuntu
 - Version 22.04

**Do you have any screenshots?**
![image](https://github.com/opensearch-project/security-analytics/assets/1134397/9fa4e713-f16f-4503-86b5-be788278e588)
